/*
 * Project name:
     mapping.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     01-05-2012
 * Time of creation
     1:00:00 PM
 * Test configuration:
     Device:          STM32F107VC
                      http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/CD00220364.pdf
     Dev.Board:       EasyMx v7 for STM32(R) ARM(R)
                      http://www.mikroe.com/easymx-pro/stm32/
     Oscillator:      HSE, 72.000MHz
     Ext. Modules:    EasyTFT
                      http://www.mikroe.com/add-on-boards/display/easytft/
                      ac:EasyTFT
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "mapping_objects.h"

void main() {

  Start_TP();

  while (1) {
    Check_TP();

  }

}